This notebook:

1. Reads a file of an MGRS tile
2. Identifies the overlapping OPERA RTC Burst IDs
3. Downloads the metadata for all the overlapping bursts from CMR/ASF
4. Saves this metadata as a parquet file
5. Downloads and organizes this data

The CMRrequests

# Get Metadata for Burst Time Series

In [33]:
from dist_s1_enumerator import get_burst_ids_in_mgrs_tiles, localize_rtc_s1_ts
from dist_s1_enumerator.asf import get_rtc_s1_ts_metadata_by_burst_ids, append_pass_data
from tqdm.auto import tqdm
import pandas as pd
import geopandas as gpd
import concurrent.futures

In [2]:
with open('MGRS_tiles.txt') as f:
    mgrs_tile_ids = f.readlines()
mgrs_tile_ids = list(map(lambda x: x.strip(), mgrs_tile_ids))
mgrs_tile_ids[:3]

['33MXU', '20KRV', '20LMK']

In [3]:
burst_ids = get_burst_ids_in_mgrs_tiles(mgrs_tile_ids)
burst_ids[:3], len(burst_ids)

(['T058-123139-IW1', 'T058-123139-IW2', 'T058-123140-IW1'], 5303)

In [9]:
%%time

df_burst_ts = gpd.GeoDataFrame()

def get_table_for_burst_id(burst_id: str) -> gpd.GeoDataFrame():
    try:
        df_burst = get_rtc_s1_ts_metadata_by_burst_ids(burst_id)
    except ValueError:
        print(f'Burst id with mixed polarizations:', burst_id)
        df_burst = gpd.GeoDataFrame()
    return df_burst       

with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
    dfs = list(tqdm(executor.map(get_table_for_burst_id, burst_ids[:]), total=len(burst_ids)))

  0%|                                                               | 0/5303 [00:00<?, ?it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  0%|                                                     | 1/5303 [00:01<2:26:48,  1.66s/it]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  0%|                                                       | 6/5303 [00:01<21:12,  4.16it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  0%|                                                      | 10/5303 [00:02<12:07,  7.28it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  0%|▏                                                     | 13/5303 [00:02<17:24,  5.06it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  0%|▏                                                     | 16/5303 [00:03<19:45,  4.46it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  0%|▏                                                     | 18/5303 [00:04<19:28,  4.52it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  0%|▏                                                     | 20/5303 [00:04<18:39,  4.72it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  0%|▏                                                     | 23/5303 [00:05<18:37,  4.72it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  1%|▎                                                     | 28/5303 [00:05<12:39,  6.95it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  1%|▎                                                     | 32/5303 [00:05<09:03,  9.69it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  1%|▎                                                     | 36/5303 [00:05<07:07, 12.32it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  1%|▍                                                     | 39/5303 [00:06<09:10,  9.57it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  1%|▍                                                     | 41/5303 [00:06<10:34,  8.30it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  1%|▌                                                     | 61/5303 [00:13<26:14,  3.33it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  1%|▋                                                     | 62/5303 [00:14<27:49,  3.14it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  1%|▋                                                     | 63/5303 [00:14<27:53,  3.13it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  1%|▋                                                     | 69/5303 [00:14<16:11,  5.39it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  1%|▋                                                     | 70/5303 [00:15<15:25,  5.66it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  1%|▊                                                     | 75/5303 [00:15<08:56,  9.74it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  2%|█▏                                                   | 121/5303 [00:35<29:15,  2.95it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  2%|█▏                                                   | 122/5303 [00:36<42:02,  2.05it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  2%|█▏                                                   | 124/5303 [00:37<47:37,  1.81it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  2%|█▏                                                   | 125/5303 [00:37<38:30,  2.24it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
  3%|█▍                                                   | 139/5303 [00:38<07:13, 11.91it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.

T127-271782-IW2
T127-271782-IW3
T127-271783-IW3
T127-271784-IW2

 23%|███████████▊                                        | 1211/5303 [06:04<39:06,  1.74it/s]

T127-271783-IW2

 23%|███████████▉                                        | 1214/5303 [06:05<27:57,  2.44it/s]

T127-271785-IW2
T127-271784-IW3

 23%|███████████▉                                        | 1216/5303 [06:05<24:53,  2.74it/s]

T127-271786-IW2
T127-271785-IW3

 23%|███████████▉                                        | 1218/5303 [06:06<24:59,  2.72it/s]

T127-271786-IW3
T127-271787-IW2

 23%|███████████▉                                        | 1220/5303 [06:07<33:24,  2.04it/s]

T127-271787-IW3

 24%|████████████▎                                       | 1253/5303 [06:18<23:35,  2.86it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 24%|████████████▎                                       | 1254/5303 [06:19<29:51,  2.26it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)

T127-271776-IW1

 24%|████████████▍                                       | 1271/5303 [06:21<11:09,  6.03it/s]

T127-271775-IW1

 24%|████████████▍                                       | 1273/5303 [06:21<10:41,  6.28it/s]

T127-271776-IW2
T127-271777-IW2

 24%|████████████▍                                       | 1274/5303 [06:21<13:10,  5.09it/s]

T127-271777-IW1

 24%|████████████▌                                       | 1276/5303 [06:22<13:50,  4.85it/s]

T127-271778-IW1
T127-271779-IW1

/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 24%|████████████▌                                       | 1277/5303 [06:23<23:36,  2.84it/s]

T127-271780-IW1
T127-271778-IW2

/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 24%|████████████▌                                       | 1280/5303 [06:24<19:23,  3.46it/s]

T127-271781-IW1

/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 24%|████████████▌                                       | 1281/5303 [06:24<19:03,  3.52it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 24%|████████████▋                                       | 1289/5303 [06:24<08:07,  8.24it/s]

T127-271782-IW1

 25%|████████████▉                                       | 1318/5303 [06:27<05:37, 11.81it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 25%|████████████▉                                       | 1320/5303 [06:27<04:59, 13.28it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 25%|████████████▉                                       | 1323/5303 [06:27<06:29, 10.21it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 26%|█████████████▎                                      | 1360/5303 [06:41<45:28,  1.45it/s]

T003-006398-IW3

/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 26%|█████████████▍                                      | 1367/5303 [06:42<20:22,  3.22it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 26%|█████████████▍                                      | 1375/5303 [06:42<10:26,  6.27it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 26%|█████████████▌                                      | 1378/5303 [06:42<10:17,  6.35it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 26%|█████████████▌                                      | 1381/5303 [06:43<08:46,  7.45it/s]

T054-114954-IW3
T054-114953-IW3
T054-114951-IW3

 26%|█████████████▌                                      | 1383/5303 [06:45<20:24,  3.20it/s]

T054-114952-IW3

 26%|█████████████▌                                      | 1386/5303 [06:45<18:25,  3.54it/s]

T054-114955-IW3
T054-114958-IW3

 26%|█████████████▌                                      | 1387/5303 [06:47<29:21,  2.22it/s]

T054-114956-IW3T054-114957-IW3

 26%|█████████████▋                                      | 1395/5303 [06:48<18:08,  3.59it/s]

T127-271748-IW2

 26%|█████████████▋                                      | 1397/5303 [06:49<21:59,  2.96it/s]

T127-271748-IW1

 26%|█████████████▋                                      | 1399/5303 [06:50<23:31,  2.77it/s]

T127-271749-IW1

 26%|█████████████▋                                      | 1400/5303 [06:51<23:36,  2.76it/s]

T127-271750-IW1
T127-271749-IW2

 26%|█████████████▋                                      | 1402/5303 [06:51<18:27,  3.52it/s]

T127-271750-IW2

 26%|█████████████▊                                      | 1403/5303 [06:51<19:04,  3.41it/s]

T127-271751-IW1

 26%|█████████████▊                                      | 1404/5303 [06:52<23:52,  2.72it/s]

T127-271751-IW2
T127-271752-IW2
T127-271753-IW2

 26%|█████████████▊                                      | 1405/5303 [06:54<42:22,  1.53it/s]

T127-271753-IW1
T127-271752-IW1

 27%|█████████████▊                                      | 1409/5303 [06:54<23:06,  2.81it/s]

T127-271754-IW1

 27%|█████████████▊                                      | 1410/5303 [06:54<21:43,  2.99it/s]

T127-271754-IW2

 27%|█████████████▊                                      | 1411/5303 [06:56<34:51,  1.86it/s]

T127-271755-IW1

 27%|██████████████                                      | 1430/5303 [07:00<12:19,  5.24it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 27%|██████████████                                      | 1431/5303 [07:01<20:43,  3.11it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 27%|██████████████                                      | 1434/5303 [07:01<14:14,  4.53it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 27%|██████████████                                      | 1439/5303 [07:01<08:06,  7.95it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 27%|██████████████▏                                     | 1442/5303 [07:02<06:30,  9.89it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 27%|██████████████▏                                     | 1444/5303 [07:02<08:08,  7.91it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 28%|██████████████▍                                     | 1474/5303 [07:15<57:58,  1.10it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 28%|██████████████▍                                     | 1477/5303 [07:18<59:26,  1.07it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 28%|██████████████▌                                     | 1479/5303 [07:19<49:35,  1.29it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 28%|██████████████▌                                     | 1480/5303 [07:21<59:53,  1.06it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 28%|██████████████▌                                     | 1483/5303 [07:21<36:09,  1.76it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 28%|██████████████▌                                     | 1486/5303 [07:22<30:29,  2.09it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 28%|██████████████▌                                     | 1487/5303 [07:22<30:31,  2.08it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 28%|██████████████▌                                     | 1488/5303 [07:24<39:14,  1.62it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 29%|███████████████                                     | 1533/5303 [07:40<31:30,  1.99it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 29%|███████████████                                     | 1535/5303 [07:41<29:27,  2.13it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 29%|███████████████▏                                    | 1547/5303 [07:42<09:05,  6.88it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 29%|███████████████▏                                    | 1550/5303 [07:43<10:22,  6.03it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 29%|███████████████▎                                    | 1557/5303 [07:43<06:16,  9.96it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 29%|███████████████▎                                    | 1561/5303 [07:43<05:11, 12.01it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 30%|███████████████▍                                    | 1579/5303 [07:47<08:54,  6.96it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 30%|███████████████▌                                    | 1581/5303 [07:47<10:02,  6.18it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 31%|████████████████                                    | 1636/5303 [08:03<11:01,  5.54it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 31%|████████████████                                    | 1638/5303 [08:03<09:51,  6.20it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 31%|████████████████                                    | 1639/5303 [08:03<10:04,  6.07it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 31%|████████████████                                    | 1644/5303 [08:04<05:38, 10.80it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 31%|████████████████▏                                   | 1649/5303 [08:04<03:34, 17.06it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 31%|████████████████▏                                   | 1653/5303 [08:04<03:03, 19.91it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)

T156-334054-IW1
T156-334055-IW1

 32%|████████████████▍                                   | 1680/5303 [08:13<18:47,  3.21it/s]

T156-334056-IW1

 32%|████████████████▍                                   | 1682/5303 [08:13<19:02,  3.17it/s]

T156-334057-IW1
T156-334058-IW1

 32%|████████████████▌                                   | 1683/5303 [08:14<21:28,  2.81it/s]

T156-334059-IW1

 32%|████████████████▌                                   | 1684/5303 [08:14<19:40,  3.07it/s]

T156-334060-IW1

 32%|████████████████▌                                   | 1691/5303 [08:19<32:44,  1.84it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 32%|████████████████▌                                   | 1694/5303 [08:22<40:58,  1.47it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 33%|████████████████▉                                   | 1724/5303 [08:30<30:04,  1.98it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 33%|████████████████▉                                   | 1726/5303 [08:30<22:37,  2.64it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 33%|█████████████████                                   | 1736/5303 [08:32<08:54,  6.68it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 33%|█████████████████                                   | 1738/5303 [08:34<17:35,  3.38it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 33%|█████████████████▏                                  | 1749/5303 [08:36<13:14,  4.47it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 33%|█████████████████▏                                  | 1751/5303 [08:36<14:07,  4.19it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 33%|█████████████████▏                                  | 1758/5303 [08:39<15:19,  3.86it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 33%|█████████████████▎                                  | 1760/5303 [08:40<19:43,  2.99it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 33%|█████████████████▎                                  | 1761/5303 [08:41<20:33,  2.87it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 33%|█████████████████▎                                  | 1765/5303 [08:41<12:24,  4.75it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 34%|████████████████▉                                 | 1791/5303 [09:00<1:12:38,  1.24s/it]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 34%|█████████████████▊                                  | 1815/5303 [09:09<19:49,  2.93it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 34%|█████████████████▊                                  | 1816/5303 [09:09<19:43,  2.95it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 34%|█████████████████▊                                  | 1818/5303 [09:10<19:08,  3.03it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 34%|█████████████████▊                                  | 1821/5303 [09:10<11:00,  5.27it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 34%|█████████████████▉                                  | 1823/5303 [09:10<08:43,  6.65it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 35%|██████████████████                                  | 1838/5303 [09:18<33:04,  1.75it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 35%|██████████████████                                  | 1842/5303 [09:20<23:10,  2.49it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 35%|██████████████████                                  | 1843/5303 [09:20<22:19,  2.58it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 35%|██████████████████                                  | 1845/5303 [09:21<28:16,  2.04it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 35%|██████████████████                                  | 1848/5303 [09:23<31:00,  1.86it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 35%|██████████████████▍                                 | 1876/5303 [09:30<17:31,  3.26it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 35%|██████████████████▍                                 | 1879/5303 [09:30<14:19,  3.99it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 35%|██████████████████▍                                 | 1881/5303 [09:30<12:21,  4.61it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 36%|██████████████████▍                                 | 1883/5303 [09:31<12:03,  4.73it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 36%|██████████████████▍                                 | 1885/5303 [09:31<10:50,  5.26it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 36%|██████████████████▊                                 | 1917/5303 [09:43<26:01,  2.17it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.
  warn('No results - please check burst id and availability.', category=UserWarning)
 36%|██████████████████▊                                 | 1922/5303 [09:43<16:28,  3.42it/s]/Users/cmarshak/bekaert-team/dist-s1-enumerator/src/dist_s1_enumerator/asf.py:99: UserWarning: No results - please check burst id and availability.

CPU times: user 7min 42s, sys: 4min 12s, total: 11min 54s
Wall time: 25min 49s

In [25]:
dfs[100].head()

,opera_id,jpl_burst_id,acq_dt,polarizations,track_number,pass_id,url_crosspol,url_copol,geometry
0,OPERA_L2_RTC-S1_T115-245678-IW2_20220104T14144...,T115-245678-IW2,2022-01-04 14:14:47+00:00,VV+VH,115,487,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,"POLYGON ((-121.18266 43.83451, -122.3128 43.97..."
1,OPERA_L2_RTC-S1_T115-245678-IW2_20220128T14144...,T115-245678-IW2,2022-01-28 14:14:46+00:00,VV+VH,115,491,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,"POLYGON ((-121.18188 43.8344, -122.312 43.9762..."
2,OPERA_L2_RTC-S1_T115-245678-IW2_20220209T14144...,T115-245678-IW2,2022-02-09 14:14:46+00:00,VV+VH,115,493,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,"POLYGON ((-121.18143 43.83426, -122.31151 43.9..."
3,OPERA_L2_RTC-S1_T115-245678-IW2_20220221T14144...,T115-245678-IW2,2022-02-21 14:14:46+00:00,VV+VH,115,495,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,"POLYGON ((-121.18263 43.83479, -122.31271 43.9..."
4,OPERA_L2_RTC-S1_T115-245678-IW2_20220305T14144...,T115-245678-IW2,2022-03-05 14:14:45+00:00,VV+VH,115,497,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,"POLYGON ((-121.18285 43.83496, -122.31288 43.9..."

In [34]:
df_burst_ts = pd.concat(dfs, axis=0)
df_burst_ts.head()

/var/folders/0p/d5x2m4tx5kg1246bplsvyfyh0000gq/T/ipykernel_24892/2893852066.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_burst_ts = pd.concat(dfs, axis=0)

,opera_id,jpl_burst_id,acq_dt,acq_date_for_mgrs_pass,polarizations,track_number,pass_id,url_crosspol,url_copol,geometry,mgrs_tile_id,acq_group_id_within_mgrs_tile,track_token
0,OPERA_L2_RTC-S1_T001-000054-IW1_20220108T18030...,T001-000054-IW1,2022-01-08 18:03:08+00:00,2022-01-08,VV+VH,1,488,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,"POLYGON ((1.54238 9.60217, 2.30972 9.75694, 2....",31PCM,0,1
1,OPERA_L2_RTC-S1_T001-000054-IW1_20220120T18030...,T001-000054-IW1,2022-01-20 18:03:07+00:00,2022-01-20,VV+VH,1,490,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,"POLYGON ((1.54341 9.60227, 2.31075 9.75702, 2....",31PCM,0,1
2,OPERA_L2_RTC-S1_T001-000054-IW1_20220201T18030...,T001-000054-IW1,2022-02-01 18:03:07+00:00,2022-02-01,VV+VH,1,492,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,"POLYGON ((1.5437 9.60213, 2.31102 9.75687, 2.2...",31PCM,0,1
3,OPERA_L2_RTC-S1_T001-000054-IW1_20220213T18030...,T001-000054-IW1,2022-02-13 18:03:07+00:00,2022-02-13,VV+VH,1,494,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,"POLYGON ((1.5426 9.60194, 2.30995 9.7567, 2.27...",31PCM,0,1
4,OPERA_L2_RTC-S1_T001-000054-IW1_20220225T18030...,T001-000054-IW1,2022-02-25 18:03:06+00:00,2022-02-25,VV+VH,1,496,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,https://datapool.asf.alaska.edu/RTC/OPERA-S1/O...,"POLYGON ((1.54243 9.60217, 2.30977 9.75694, 2....",31PCM,0,1

In [35]:
%%time

df_burst_ts.to_parquet('burst_ts.parquet', compression='zstd', index=None)

CPU times: user 656 ms, sys: 384 ms, total: 1.04 s
Wall time: 1.58 s

# Serialize Data

In [43]:
# This updates metadata to include MGRS info; also for downloading data using dist-s1-enumerator which has column validation
df_burst_ts = append_pass_data(df_burst_ts, mgrs_tile_ids)

# I am not sure why these are not correctly typed.
df_burst_ts.track_number = df_burst_ts.track_number.astype(int)
df_burst_ts.pass_id = df_burst_ts.pass_id.astype(int)

In [53]:
%%time

df_burst_ts_loc = localize_rtc_s1_ts(df_burst_ts[:], 'out/burst_ts_data', tqdm_enabled=True, max_workers=5)
df_burst_ts_loc.head()

Downloading RTC-S1 burst data:   0%|               | 1376/448218 [23:18<126:11:27,  1.02s/it]

KeyboardInterrupt:

In [ ]:
%%time

df_burst_ts_loc.to_parquet('burst_ts_loc.parquet', compression='zstd', index=None)